### ISSUE TITLE
Feature Vector Dimensions Mismatch

### ISSUE THREAD

**Issue by ahmad-bashir9** [zzc-1998/NR-QA-for-point-cloud#2]
Hello,

I was evaluating your code. The paper says it gives 88 feature values for 3D Point Clouds but feature_extract.py returns 64 values feature vector. Can you please explain the reason why is it doing so?
Thank you

**Comment by zzc-1998** [comment]
Hello,
We explain in the Experiment Update section of the project page that 'We do not use the GGD, AGGD, Gamma parameters of color features in this experiment version for simplification.', which is why only 64 values are returned. By using the returned 64 values, you should get the performance results with no drop as reported in the paper.
Thank you for your question.

**Comment by ahmad-bashir9** [comment]
Okay, thank you. I have another question @zzc-1998 

Can you please explain a bit what is the range of predicted scores for a point cloud and how can we interpret it?

**Comment by zzc-1998** [comment]
The range of the predicted scores depends on the MOSs' range since the model is trained to give predicted scores close to MOSs. 
Thank you for your question.
